# Generated by Django 4.1.7 on 2023-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_image', models.JSONField()),
            ],
        ),
    ]
