# Generated by Django 4.1.7 on 2023-03-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_citi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citi',
            old_name='id_image',
            new_name='image_ids',
        ),
    ]
