# Generated by Django 4.1.7 on 2023-03-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_id_image_citi_image_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citi',
            new_name='City',
        ),
    ]
