# Generated by Django 4.1.7 on 2023-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_heroes_delete_city_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ans', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
    ]
