# Generated by Django 4.1.7 on 2023-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_answers_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='heroes',
            name='possible_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
