# Generated by Django 4.1.7 on 2023-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_items_heroes_possible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
