# Generated by Django 4.1.7 on 2023-03-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
