# Generated by Django 4.1.7 on 2023-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newpossiblenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='image_id',
            field=models.TextField(default=''),
        ),
    ]
